# 98_make_dummy_completed_validation_files.R
# ------------------------------------------------------------
# OPTIONAL TEST SCRIPT ONLY. Do not use for final manuscript values.
#
# Purpose:
#   Create artificial completed validator/coauthor validation CSV files from the
#   validation templates generated by scripts/15_validation_audits.R.
#   This lets you test that the agreement/validation-metric code runs before
#   the real coauthor files are returned.
#
# How to test:
#   1) source("scripts/99_run_validation_audits.R", encoding = "UTF-8")
#      # this creates outputs/validation/validation_files_by_validator/
#   2) source("scripts/98_make_dummy_completed_validation_files.R", encoding = "UTF-8")
#      # this creates artificial completed files under outputs/validation/completed/
#   3) source("scripts/99_run_validation_audits.R", encoding = "UTF-8")
#      # this reads those completed files and exports metrics tables
#
# Delete or overwrite the dummy completed files before using real coauthor data.
# ------------------------------------------------------------

suppressPackageStartupMessages({
  library(readr)
  library(dplyr)
  library(stringr)
})

set.seed(20260611)

src_root <- file.path("outputs", "validation", "validation_files_by_validator")
dst_root <- file.path("outputs", "validation", "completed", "validation_files_by_validator")

if (!dir.exists(src_root)) {
  stop("Validator template folder not found: ", src_root,
       "\nRun source('scripts/99_run_validation_audits.R', encoding = 'UTF-8') first.")
}

template_files <- list.files(src_root, pattern = "[.]csv$", recursive = TRUE, full.names = TRUE)

template_files <- template_files[
  str_detect(basename(template_files), regex("LABEL_Iberia_relevance_validation|LABEL_iberian_relevance_validation|keyword_category_validation|keyword_occurrence_validation", ignore_case = TRUE)) &
    !str_detect(basename(template_files), regex("template_all_records|assignment_summary|decision_rules|category_rules", ignore_case = TRUE))
]

if (length(template_files) == 0) {
  stop("No validator-specific validation files found in: ", src_root)
}

random_other_category <- function(x) {
  cats <- c("Invasion", "Detection", "eCommerce", "Threat")
  vapply(x, function(z) {
    choices <- setdiff(cats, z)
    if (length(choices) == 0) choices <- cats
    sample(choices, 1)
  }, character(1))
}

for (f in template_files) {
  rel <- sub(paste0("^", gsub("([\\\\.\\+\\*\\?\\^\\$\\(\\)\\[\\]\\{\\}\\|])", "\\\\\\1", src_root), "/?"), "", f)
  out <- file.path(dst_root, rel)
  dir.create(dirname(out), recursive = TRUE, showWarnings = FALSE)

  dat <- readr::read_csv(f, show_col_types = FALSE)
  fn <- basename(f)

  if (str_detect(fn, regex("LABEL", ignore_case = TRUE))) {
    if (!"validator2_is_iberian" %in% names(dat)) dat$validator2_is_iberian <- NA_character_
    n <- nrow(dat)
    # Mostly TRUE, with a few FALSE and UNCERTAIN rows to test false-positive and uncertainty summaries.
    dat$validator2_is_iberian <- sample(c("TRUE", "FALSE", "UNCERTAIN"), n, replace = TRUE,
                                       prob = c(0.82, 0.10, 0.08))
    dat$validator2_evidence <- dplyr::case_when(
      dat$validator2_is_iberian == "TRUE" ~ "Dummy test: Iberian cue judged sufficient",
      dat$validator2_is_iberian == "FALSE" ~ "Dummy test: non-Iberian or insufficient context",
      TRUE ~ "Dummy test: uncertain context"
    )
    dat$validator2_exclusion_reason <- ifelse(dat$validator2_is_iberian == "FALSE", "Dummy non-Iberian/unclear relevance", "")
    dat$validator2_confidence <- sample(c("high", "medium", "low"), n, replace = TRUE,
                                       prob = c(0.55, 0.35, 0.10))
    dat$validator2_notes <- "Artificial test value generated by 98_make_dummy_completed_validation_files.R"
  }

  if (str_detect(fn, regex("keyword", ignore_case = TRUE))) {
    if (!"manual_category" %in% names(dat)) dat$manual_category <- NA_character_
    if (!"manual_valid" %in% names(dat)) dat$manual_valid <- NA_character_
    if (!"manual_ambiguous" %in% names(dat)) dat$manual_ambiguous <- NA_character_
    n <- nrow(dat)
    auto <- as.character(dat$KeywordCategory)
    outcome <- sample(c("match", "mismatch", "ambiguous", "none"), n, replace = TRUE,
                      prob = c(0.78, 0.10, 0.07, 0.05))
    dat$manual_category <- dplyr::case_when(
      outcome == "match" ~ auto,
      outcome == "mismatch" ~ random_other_category(auto),
      outcome == "ambiguous" ~ "Ambiguous",
      outcome == "none" ~ "None",
      TRUE ~ auto
    )
    dat$manual_valid <- ifelse(dat$manual_category == "None", "FALSE", "TRUE")
    dat$manual_ambiguous <- ifelse(dat$manual_category == "Ambiguous", "TRUE", "FALSE")
    dat$manual_notes <- "Artificial test value generated by 98_make_dummy_completed_validation_files.R"
  }

  readr::write_csv(dat, out, na = "")
  message("Dummy completed file written: ", out)
}

message("\nDummy completed validation files are ready in: ", dst_root)
message("Now rerun: source('scripts/99_run_validation_audits.R', encoding = 'UTF-8')")
message("Important: delete/replace these dummy files before using final coauthor validation data.")
