# Keyword lists used to classify title, description and comment tokens.
# English terms were removed from the shared version.

# Keyword lists for thematic categories
# Threat
Threat <- c(
  # Spanish (Español)
  "Amenaza", "amenaza",
  "Amenaza a la biodiversidad", "amenaza a la biodiversidad",
  "Biodiversidad en peligro", "biodiversidad en peligro",
  "Daño ambiental", "daño ecológico", "perjuicio ecológico",
  "Cambio de hábitat", "Cambio de habitat", "cambio de hábitat", "cambio de habitat",
  "Competencia", "competencia",
  "Contagio", "contagio",
  "Contaminación", "contaminación",
  "Foco de contaminación", "foco de contaminación", "Focos de contaminación", "focos de contaminación",
  "Foco de infección", "foco de infección", "Focos de infección", "focos de infección",
  "Ataca", "ataca", "Atacando", "atacando", "Atacado", "atacado", "Atacada", "atacada",
  "Dañina", "danina", "Dañino", "danino",
  "Degradación", "Degradacion", "degradación", "degradacion",
  "Epidemia", "epidemia",
  "Extinción", "Extincion", "extinción", "extincion",
  "Hibridación", "Hibridacion", "hibridación", "hibridacion",
  "Impacto negativo", "impacto ambiental", "impacto ecológico",
  "Letal", "letal", "Letalidad", "letalidad",
  "Nociva", "nociva", "Nocivo", "nocivo",
  "Pandemia", "pandemia",
  "Peligro", "peligro",
  "Peligrosa", "peligrosa", "Peligroso", "peligroso",
  "Perjudicial", "perjudicial",
  "Riesgo", "riesgo", "Riesgo sanitario", "riesgo sanitario",
  "Sobrepoblación", "Sobrepoblacion", "sobrepoblación", "sobrepoblacion",
  "Tóxica", "Toxica", "tóxica", "toxica",
  "Tóxico", "Toxico", "tóxico", "toxico",
  "Toxicidad", "toxicidad",
  "Transmisor", "transmisor", "Transmisora", "transmisora",
  "Vector", "vector",
  "Veneno", "veneno",
  "Venenosa", "venenosa", "Venenoso", "venenoso",
  "Virus", "virus",
  "Infección bacteriana", "infección bacteriana",

  # Portuguese (Portugal)
  "Ameaça", "ameaça",
  "Ameaça à biodiversidade", "ameaça à biodiversidade",
  "Biodiversidade em perigo", "biodiversidade em perigo",
  "Dano ambiental", "dano ecológico", "prejuízo ecológico",
  "Mudança de habitat", "Mudanca de habitat", "mudança de habitat", "mudanca de habitat",
  "Competição", "competição",
  "Contágio", "contágio",
  "Contaminação", "contaminação",
  "Foco de contaminação", "foco de contaminação", "Focos de contaminação", "focos de contaminação",
  "Foco de infeção", "foco de infeção", "Focos de infeção", "focos de infeção",
  "Ataca", "a atacar", "Atacando", "atacando", "Atacado", "atacado", "Atacada", "atacada",
  "Daninha", "daninha", "Daninho", "daninho",
  "Degradação", "degradação",
  "Epidemia", "epidemia",
  "Extinção", "Extincao", "extinção", "extincao",
  "Hibridação", "Hibridacao", "hibridação", "hibridacao",
  "Impacto negativo", "impacto ambiental",
  "Letal", "letal", "Letalidade", "letalidade",
  "Nociva", "nociva", "Nocivo", "nocivo",
  "Pandemia", "pandemia",
  "Perigo", "perigo",
  "Perigosa", "perigosa", "Perigoso", "perigoso",
  "Prejudicial", "prejudicial",
  "Risco", "risco", "Risco sanitário", "risco sanitário",
  "Superpopulação", "Superpopulacao", "superpopulação", "superpopulacao",
  "Tóxica", "Toxica", "tóxica", "toxica",
  "Tóxico", "Toxico", "tóxico", "toxico",
  "Toxicidade", "toxicidade",
  "Transmissor", "transmissor", "Transmissora", "transmissora",
  "Vetor", "vetor",
  "Veneno", "veneno",
  "Venenosa", "venenosa", "Venenoso", "venenoso",
  "Vírus", "vírus",
  "Infeção bacteriana", "infeção bacteriana",

  # Catalan (Català)
  "Amenaça", "amenaça",
  "Amenaça a la biodiversitat", "amenaça a la biodiversitat",
  "Biodiversitat en perill", "biodiversitat en perill",
  "Dany ambiental", "dany ecològic", "perjudici ecològic",
  "Canvi d'hàbitat", "Canvi d'habitat", "canvi d'hàbitat", "canvi d'habitat",
  "Competència", "competència",
  "Contagi", "contagi",
  "Contaminació", "contaminació",
  "Foc de contaminació", "foc de contaminació", "Focs de contaminació", "focs de contaminació",
  "Foc d'infecció", "foc d'infecció", "Focs d'infecció", "focs d'infecció",
  "Ataca", "ataca", "Atacant", "atacant", "Atacat", "atacat", "Atacada", "atacada",
  "Danyina", "danyina", "Nociu", "nociu",
  "Degradació", "degradació",
  "Epidèmia", "epidèmia",
  "Extinció", "extinció",
  "Hibridació", "hibridació",
  "Impacte negatiu", "impacte ecològic",
  "Letal", "letal",
  "Nociva", "nociva",
  "Pandèmia", "pandèmia",
  "Perill", "perill",
  "Perillosa", "perillosa", "Perillós", "perillós",
  "Prejudicial", "prejudicial",
  "Risc", "risc", "Risc sanitari", "risc sanitari",
  "Superpoblació", "superpoblació",
  "Tòxica", "tòxica",
  "Tòxic", "tòxic",
  "Toxicitat", "toxicitat",
  "Transmissor", "transmissor", "Transmissora", "transmissora",
  "Vector", "vector",
  "Verí", "verí",
  "Verinosa", "verinosa", "Verinós", "verinós",
  "Virus", "virus",
  "Infecció bacteriana", "infecció bacteriana",

  # Galician (Galego)
  "Ameaza", "ameaza",
  "Ameaza á biodiversidade", "ameaza a biodiversidade",
  "Biodiversidade en perigo", "biodiversidade en perigo",
  "Dano ambiental", "dano ecolóxico", "prexuízo ecolóxico",
  "Cambio de hábitat", "Cambio de habitat", "cambio de hábitat", "cambio de habitat",
  "Competencia", "competencia",
  "Contaxio", "contaxio",
  "Contaminación", "contaminación",
  "Foco de contaminación", "foco de contaminación", "Focos de contaminación", "focos de contaminación",
  "Foco de infección", "foco de infección", "Focos de infección", "focos de infección",
  "Ataca", "ataca", "Atacando", "atacando", "Atacada", "atacada", "Atacado", "atacado",
  "Dañina", "danina", "Dañino", "danino",
  "Degradación", "degradación",
  "Epidemia", "epidemia",
  "Extinción", "extinción",
  "Hibridación", "hibridación",
  "Impacto negativo", "impacto ecolóxico",
  "Letal", "letal", "Letalidade", "letalidade",
  "Nociva", "nociva", "Nocivo", "nocivo",
  "Pandemia", "pandemia",
  "Perigo", "perigo",
  "Perigosa", "perigosa", "Perigoso", "perigoso",
  "Prexudicial", "prexudicial",
  "Risco", "risco", "Risco sanitario", "risco sanitario",
  "Superpoboación", "superpoboación",
  "Tóxica", "tóxica",
  "Tóxico", "tóxico",
  "Toxicidade", "toxicidade",
  "Transmisor", "transmisor",
  "Vector", "vector",
  "Veneno", "veneno",
  "Venenosa", "venenosa", "Venenoso", "venenoso",
  "Virus", "virus",
  "Infección bacteriana", "infección bacteriana",

  # Basque (Euskara)
  "Mehatxua", "mehatxua",
  "Bioaniztasunari mehatxua", "bioaniztasuna arriskuan",
  "Ingurumen-kalte", "ingurumenari kalte",
  "Habitat-aldaketa", "habitat aldaketa",
  "Lehiakortasuna", "lehiakortasuna",
  "Kutsadura", "kutsadura",
  "Kontaminazioa", "kontaminazioa",
  "Kontaminazio-fokoa", "kontaminazio-fokoa", "Kontaminazio-fokuak", "kontaminazio-fokuak",
  "Infekzio-fokoa", "infekzio-fokoa", "Infekzio-fokuak", "infekzio-fokuak",
  "Erasoa", "erasoa", "Erasotzen", "erasotzen", "Erasoa du", "erasoa du",
  "Kaltegarria", "kaltegarria",
  "Degradazioa", "degradazioa",
  "Epidemia", "epidemia",
  "Desagerpena", "desagerpena", "extinkzioa",
  "Hibridazioa", "hibridazioa",
  "Eragin negatiboa", "eragin ekologikoa",
  "Hilgarria", "hilgarria",
  "Arriskua", "arriskua", "Osasun-arriskua", "osasun arriskua",
  "Gainpopulazioa", "gainpopulazioa",
  "Toxikoa", "toxikoa", "Toxikotasuna", "toxikotasuna",
  "Transmisorea", "transmisorea",
  "Bektorea", "bektorea",
  "Pozoia", "pozoia",
  "Pozoitsua", "pozoitsua",
  "Birusa", "birusa",
  "Bakterio-infekzioa", "bakterio infekzioa",

  # Asturian (Asturianu)
  "Amenaza", "amenaza",
  "Amenaza a la biodiversidá", "biodiversidá en peligru",
  "Dañu ambiental", "dañu ecolóxicu", "perxuiciu ecolóxicu",
  "Cambu de hábitat", "cambu de habitat",
  "Competencia", "competencia",
  "Contaxu", "contaxu",
  "Contaminación", "contaminación",
  "Focu de contaminación", "focu de contaminación", "Focos de contaminación", "focos de contaminación",
  "Focu d'infeición", "focu d'infeición", "Focos d'infeición", "focos d'infeición",
  "Ataca", "ataca", "Atacando", "atacando", "Atacada", "atacada", "Atacáu", "atacáu",
  "Dañina", "dañina", "Dañín", "dañín",
  "Degradación", "degradación",
  "Epidemia", "epidemia",
  "Estinción", "estinción",
  "Hibridación", "hibridación",
  "Impactu negativu", "impactu ecolóxicu",
  "Letal", "letal", "Letalidá", "letalidá",
  "Nociva", "nociva", "Nocivu", "nocivu",
  "Pandemia", "pandemia",
  "Peligru", "peligru",
  "Peligrosa", "peligrosa", "Peligrosu", "peligrosu",
  "Perxudicial", "perxudicial",
  "Riesgu", "riesgu", "Riesgu sanitariu", "riesgu sanitariu",
  "Sobrepoblación", "sobrepoblación",
  "Tóxica", "tóxica",
  "Tóxicu", "tóxicu",
  "Toxicidá", "toxicidá",
  "Tresmisor", "tresmisor", "Tresmisora", "tresmisora",
  "Vector", "vector",
  "Veníu", "veníu",
  "Venenosa", "venenosa", "Venenosu", "venenosu",
  "Virus", "virus",
  "Infeición bacteriana", "infeición bacteriana"
)


# Invasion
Invasion <- c(
  # Spanish (Español)
  "Alíen", "alíen",
  "Colonización", "Colonizacion", "colonización", "colonizacion",
  "colonization",
  "EEI", "EEIS", "EEIs",
  "Exótica", "Exotica", "exótica", "exotica",
  "Exótico", "Exotico", "exótico", "exotico",
  "Especie exótica", "especie exótica", "Especie invasora", "especie invasora",
  "Especies exóticas invasoras", "especies exóticas invasoras",
  "Exótica naturalizada", "exótica naturalizada", "naturalizada",
  "Especie naturalizada", "especie naturalizada",
  "Expansión", "Expansion", "expansión", "expansion",
  "Invasión", "Invasion", "invasión", "invasion",
  "Invasor", "invasor", "Invasores", "invasores",
  "Invasora", "invasora", "Invasoras", "invasoras",
  "Introducción", "Introduccion", "introducción", "introduccion",
  "Introducida", "introducida", "Introducidas", "introducidas",
  "Invade", "invade",
  "Proliferación", "proliferación", "proliferacion",
  "Difusión", "difusión", "difusion",
  "Nativa", "nativa", "native",
  "No nativa", "no nativa", "no native",
  "Plaga", "plaga", "Plagas", "plagas",
  "plagues",
  "ya presente", "presente",
  "Extendida", "Extendido", "Extensión",
  # Spanish (Español)
  "Foco de invasión", "foco de invasión", "Focos de invasión", "focos de invasión",
  "Frente de invasión", "frente de invasión",
  "En expansión", "expansión rápida", "rápida expansión",
  "Establecida", "establecida", "Establecido", "establecido",
  "Reproduciéndose", "reproduciéndose", "Se multiplica", "se multiplica",
  "Afectando", "afectando",

  # Portuguese (Portugal)
  "Espécies Exóticas Invasoras", "espécies exóticas invasoras",
  "Espécie exótica", "espécie exótica",
  "Espécie invasora", "espécie invasora",
  "Exótica naturalizada", "exótica naturalizada", "naturalizada",
  "Colonização", "Colonizacao", "colonização", "colonizacao",
  "Expansão", "Expansao", "expansão", "expansao",
  "Invasão", "Invasao", "invasão", "invasao",
  "Invasor", "invasor", "Invasores", "invasores",
  "Invasora", "invasora", "Invasoras", "invasoras",
  "Introdução", "Introducao", "introdução", "introducao",
  "Introduzida", "introduzida", "Introduzidas", "introduzidas",
  "Invadir", "invadir",
  "Proliferação", "proliferação", "proliferacao",
  "Dispersão", "dispersão", "dispersao",
  "Nativa", "nativa",
  "Não nativa", "Nao nativa", "não nativa", "nao nativa",
  "Praga", "praga", "Pragas", "pragas",
  # Portuguese (Portugal)
  "Foco de invasão", "foco de invasão", "Focos de invasão", "focos de invasão",
  "Frente de invasão", "frente de invasão",
  "Em expansão", "expansão rápida",
  "Estabelecida", "estabelecida", "Estabelecido", "estabelecido",
  "A reproduzir-se", "a reproduzirse", "Multiplica-se", "multiplica-se",
  "A afectar", "a afetar", "a afectar",

  # Catalan (Català)
  "Aliena", "aliena",
  "Colonització", "Colonitzacio", "colonització", "colonitzacio",
  "Expansió", "Expansio", "expansió", "expansio",
  "Invasió", "Invasio", "invasió", "invasio",
  "Invasor", "invasor", "Invasors", "invasors",
  "Invasora", "invasora", "Invasores", "invasores",
  "Introducció", "Introduccio", "introducció", "introduccio",
  "Introduïda", "Introduida", "introduïda", "introduida",
  "Proliferació", "proliferació", "proliferacio",
  "Difusió", "difusió", "difusio",
  "Nativa", "nativa",
  "No nativa", "no nativa",
  "Plaga", "plaga", "plagues",
  "ja present",
  # Catalan (Català)
  "Foc d'invasió", "foc d'invasió", "Focs d'invasió", "focs d'invasió",
  "Front d'invasió", "front d'invasió",
  "En expansió", "expansió ràpida",
  "Establerta", "establerta", "Establert", "establert",
  "Reproduint-se", "reproduint-se", "Es multiplica", "es multiplica",
  "Afectant", "afectant",

  # Galician (Galego)
  "Aliena", "aliena",
  "Colonización", "Colonizacion", "colonización", "colonizacion",
  "Expansión", "Expansion", "expansión", "expansion",
  "Invasión", "Invasion", "invasión", "invasion",
  "Invasor", "invasor", "Invasores", "invasores",
  "Invasora", "invasora", "Invasoras", "invasoras",
  "Introdución", "Introducion", "introdución", "introducion",
  "Introducida", "introducida", "Introducidas", "introducidas",
  "Proliferación", "proliferación", "proliferacion",
  "Difusión", "difusión", "difusion",
  "Nativa", "nativa",
  "Non nativa", "non nativa",
  "Praga", "praga", "Pragas", "pragas",
  # Galician (Galego)
  "Foco de invasión", "foco de invasión", "Focos de invasión", "focos de invasión",
  "Fronte de invasión", "fronte de invasión",
  "En expansión", "expansión rápida",
  "Establecida", "establecida", "Establecido", "establecido",
  "Reproducíndose", "reproducíndose", "Multiplícase", "multiplícase",
  "Afectando", "afectando",

  # Basque (Euskara)
  "Arrotza", "arrotza", "Arrotz", "arrotz",
  "Kolonizazioa", "Kolonizazio", "kolonizazioa", "kolonizazio",
  "Hedapena", "hedapena", "Hedapen", "hedapen",
  "Inbasioa", "Inbasio", "inbasioa", "inbasio",
  "Inbaditzailea", "inbaditzailea", "Inbaditzaileak", "inbaditzaileak",
  "Sarrera", "sarrera", "Sartuak", "sartuak",
  "Sartutakoa", "sartutakoa", "Sartutakoak", "sartutakoak",
  "Ugaritzea", "ugaritzea", "Ugaritu", "ugaritu",
  "Zabalkundea", "zabalkundea",
  "Natatiboa", "natatiboa",   # (manteniendo entrada previa, aún si es dudosa)
  "Ez natatiboa", "ez natatiboa",
  "Izurria", "izurria", "Izurriak", "izurriak",
  "dagoeneko presente",
  # Basque (Euskara)
  "Inbasio-fokoa", "inbasio fokoa", "Inbasio-fokuak", "inbasio fokuak",
  "Inbasio-frontea", "inbasio frontea",
  "Hedapenean", "hedapenean",
  "Ezarrita", "ezarrita",
  "Ugaltzen", "ugaltzen", "Ugaltzen ari da", "ugaltzen ari da",
  "Eragiten", "eragiten",

  # Asturian (Asturianu)
  "Alienígena", "alienígena", "Alienigena", "alienigena",
  "Colonización", "Colonizacion", "colonización", "colonizacion",
  "Espansión", "Espansion", "espansión", "espansion",
  "Invasión", "Invasion", "invasión", "invasion",
  "Invasor", "invasor", "Invasores", "invasores",
  "Invasora", "invasora", "Invasoras", "invasoras",
  "Introducción", "Introduccion", "introducción", "introduccion",
  "Introducida", "introducida", "Introducidas", "introducidas",
  "Proliferación", "proliferación", "proliferacion",
  "Difusión", "difusión", "difusion",
  "Nativa", "nativa",
  "Non nativa", "non nativa",
  "Plaga", "plaga", "plagues",
  # Asturian (Asturianu)
  "Focu d'invasión", "focos d'invasión",
  "Frente d'invasión", "frente d'invasión",
  "En espansión", "espansión rápida",
  "Establecida", "establecida", "Establecíu", "establecíu",
  "Reproduciéndose", "reproduciéndose", "Multiplicándose", "multiplicándose",
  "Afectando", "afectando",
  
  # Spanish (Español)
  "Propagación", "Propagacion", "propagación", "propagacion",
  "Propagarse", "propagarse", "Se propaga", "se propaga", "Propagando", "propagando",
  "Dispersión", "Dispersion", "dispersión", "dispersion",
  "Dispersarse", "dispersarse", "Se dispersa", "se dispersa", "Dispersándose", "dispersándose",

  # Portuguese (Portugal)
  "Propagação", "Propagacao", "propagação", "propagacao",
  "Propagar-se", "propagar-se", "Propaga-se", "propaga-se", "A propagar-se", "a propagar-se",
  "Dispersão", "Dispersao", "dispersão", "dispersao",
  "Dispersar-se", "dispersar-se", "Dispersa-se", "dispersa-se",

  # Catalan (Català)
  "Propagació", "Propagacio", "propagació", "propagacio",
  "Propagar-se", "propagar-se", "Es propaga", "es propaga",
  "Dispersió", "Dispersio", "dispersió", "dispersio",
  "Dispersar-se", "dispersar-se", "Es dispersa", "es dispersa",

  # Galician (Galego)
  "Propagación", "Propagacion", "propagación", "propagacion",
  "Propagarse", "propagarse", "Propágase", "propágase",
  "Dispersión", "Dispersion", "dispersión", "dispersion",
  "Dispersarse", "dispersarse", "Dispérsase", "dispérsase",

  # Basque (Euskara)
    "Hedapena", "hedapena", "Hedatu", "hedatu", "Hedatzen", "hedatzen", "Hedatzen da", "hedatzen da",
  "Zabalkundea", "zabalkundea", "Zabaldu", "zabaldu", "Zabaltzen", "zabaltzen", "Zabaltzen da", "zabaltzen da",
    "Sakabanaketa", "sakabanaketa",
  "Dispertsioa", "dispertsioa", "Dispertsatu", "dispertsatu", "Dispertsatzen", "dispertsatzen", "Dispertsatzen da", "dispertsatzen da",

  # Asturian (Asturianu)
  "Propagación", "Propagacion", "propagación", "propagacion",
  "Propagar", "propagar", "Propagándose", "propagándose",
  "Dispersión", "Dispersion", "dispersión", "dispersion",
  "Dispersar", "dispersar", "Dispersándose", "dispersándose"
)

Detection <- c(
  # Spanish (Español)
  "Aparición", "Aparicion", "aparición", "aparicion",
  "Alerta", "alerta",
  "Avistamiento", "avistamiento", "avistado", "avistada", "avistados", "avistadas",
  "Descubrimiento", "descubrimiento",
  "Detección", "Deteccion", "detección", "deteccion",
  "Detectada", "detectada", "Detectado", "detectado",
  "Encontrada", "encontrada", "Encontrado", "encontrado",
  "Encontré", "encontré", "He encontrado", "he encontrado", "Hemos encontrado", "hemos encontrado",
  "Identificada", "identificada", "Identificado", "identificado",
  "Monitorización", "Monitorizacion", "monitorización", "monitorizacion",
  "Notificación", "Notificacion", "notificación", "notificacion",
  "Observada", "observada", "Observado", "observado",
  "Reciente", "reciente",
  "Registro", "registro",
  "Seguimiento", "seguimiento",

  # Spanish (Español)
  "Monitoreo", "monitoreo",
  "Monitorear", "monitorear", "Monitoreando", "monitoreando",
  "Monitoreado", "monitoreado", "Monitoreada", "monitoreada",
  "Rastreo", "rastreo",
  "Rastrear", "rastrear", "Rastreado", "rastreado", "Rastreada", "rastreada",
  "Trazado", "trazado",

  # Spanish (Español)
  "Descubierta", "descubierta", "Descubierto", "descubierto", "Descubiertas", "descubiertas", "Descubiertos", "descubiertos",
  "Hallazgo", "hallazgo", "Hallazgos", "hallazgos",
  "Hallada", "hallada", "Hallado", "hallado", "Halladas", "halladas", "Hallados", "hallados",
  "Vista", "vista", "Visto", "visto", "Vistas", "vistas", "Vistos", "vistos",
  "Aparecida", "aparecida", "Aparecido", "aparecido", "Aparecidas", "aparecidas", "Aparecidos", "aparecidos",
  "Aparece", "aparece", "Aparecieron", "aparecieron",

  # Portuguese (Portugal)
  "Aparição", "Aparicao", "aparição", "apariçao",
  "Alerta", "alerta",
  "Avistamento", "avistamento",
  "Descoberta", "descoberta",
  "Detecção", "Deteccao", "detecção", "deteccao",
  "Detectada", "detectada", "Detectado", "detectado",
  "Encontrada", "encontrada", "Encontrado", "encontrado",
  "Encontrei", "encontrei", "Encontrei-a", "encontrei-a", "Encontrei-o", "encontrei-o",
  "Encontrei-os", "encontrei-os", "Encontrei-as", "encontrei-as",
  "Encontrei algo", "encontrei algo", "Encontrámos", "encontrámos", "Encontramos", "encontramos",
  "Identificada", "identificada", "Identificado", "identificado",
  "Monitoramento", "monitoramento",
  "Notificação", "Notificacao", "notificação", "notificacao",
  "Observada", "observada", "Observado", "observado",
  "Recente", "recente",
  "Registro", "registro",
  "Acompanhamento", "acompanhamento",

  # Portuguese (Portugal)
  "Monitorização", "Monitorizacao", "monitorização", "monitorizacao",
  "Monitorizar", "monitorizar", "Monitorizado", "monitorizado", "Monitorizada", "monitorizada",
  "Monitorar", "monitorar", "Monitorado", "monitorado", "Monitorada", "monitorada",
  "Rastreamento", "rastreamento", "Rastreio", "rastreio",
  "Rastrear", "rastrear", "Rastreado", "rastreado", "Rastreada", "rastreada",

  # Portuguese (Portugal)
  "Descoberto", "descoberto", "Descoberta", "descoberta", "Descobertos", "descobertos", "Descobertas", "descobertas",
  "Achado", "achado", "Achada", "achada", "Achados", "achados", "Achadas", "achadas",
  "Visto", "visto", "Vista", "vista", "Vistos", "vistos", "Vistas", "vistas",
  "Aparecido", "aparecido", "Aparecida", "aparecida", "Aparecidos", "aparecidos", "Aparecidas", "aparecidas",
  "Aparece", "aparece", "Apareceram", "apareceram",

  # Catalan (Català)
  "Aparició", "Aparicio", "aparició", "aparicio",
  "Alerta", "alerta",
  "Avistament", "avistament", "avistat",
  "Descobriment", "descobriment",
  "Detecció", "Deteccio", "detecció", "deteccio",
  "Detectada", "detectada", "Detectat", "detectat",
  "He trobat", "he trobat", "Hem trobat", "hem trobat", "Vaig trobar", "vaig trobar",
  "Identificada", "identificada", "Identificat", "identificat",
  "Monitorització", "Monitoritzacio", "monitorització", "monitoritzacio",
  "Notificació", "Notificacio", "notificació", "notificacio",
  "Observada", "observada", "Observat", "observat",
  "Recent", "recent",
  "Registre", "registre",
  "Seguiment", "seguiment",

  # Catalan (Català)
  "Monitoratge", "monitoratge",
  "Monitoritzar", "monitoritzar", "Monitoritzat", "monitoritzat", "Monitoritzada", "monitoritzada",
  "Rastreig", "rastreig",
  "Rastrejar", "rastrejar", "Rastrejat", "rastrejat", "Rastrejada", "rastrejada",

  # Catalan (Català)
  "Descobert", "descobert", "Descoberta", "descoberta", "Descoberts", "descoberts", "Descobertes", "descobertes",
  "Troballa", "troballa", "Trobades", "trobades", "Troballes", "troballes",
  "Vist", "vist", "Vista", "vista", "Vistos", "vistos", "Vistes", "vistes",
  "Aparegut", "aparegut", "Apareguda", "apareguda", "Apareguts", "apareguts", "Aparegudes", "aparegudes",
  "Apareix", "apareix", "Han aparegut", "han aparegut",

  # Galician (Galego)
  "Aparición", "Aparicion", "aparición", "aparicion",
  "Alerta", "alerta",
  "Avistamento", "avistamento",
  "Descubrimento", "descubrimento",
  "Detección", "Deteccion", "detección", "deteccion",
  "Detectada", "detectada", "Detectado", "detectado",
  "Atopada", "atopada", "Atopado", "atopado",
  "Atopei", "atopei", "Atopamos", "atopamos",
  "Identificada", "identificada", "Identificado", "identificado",
  "Monitorización", "Monitorizacion", "monitorización", "monitorizacion",
  "Notificación", "Notificacion", "notificación", "notificacion",
  "Observada", "observada", "Observado", "observado",
  "Recentemente", "recentemente",
  "Rexistro", "rexistro",
  "Seguimento", "seguimento",

  # Galician (Galego)
  "Monitoreo", "monitoreo",
  "Monitorizar", "monitorizar", "Monitorizado", "monitorizado", "Monitorizada", "monitorizada",
  "Rastrexo", "rastrexo",
  "Rastrexar", "rastrexar", "Rastrexado", "rastrexado", "Rastrexada", "rastrexada",

  # Galician (Galego)
  "Descuberto", "descuberto", "Descuberta", "descuberta", "Descubertos", "descubertos", "Descubertas", "descubertas",
  "Achado", "achado", "Achada", "achada", "Achados", "achados", "Achadas", "achadas",
  "Visto", "visto", "Vista", "vista", "Vistos", "vistos", "Vistas", "vistas",
  "Aparecido", "aparecido", "Aparecida", "aparecida", "Aparecidos", "aparecidos", "Aparecidas", "aparecidas",
  "Aparece", "aparece", "Apareceron", "apareceron",

  # Basque (Euskara)
  "Agerpena", "agerpena",
  "Alerta", "alerta",
  "Behaketa", "behaketa", "ikusmen",
  "Aurkikuntza", "aurkikuntza",
  "Detekzioa", "detekzioa",
  "Atzemandakoa", "atzemandakoa",
  "Aurkitua", "aurkitua", "Aurkitu dut", "aurkitu dut", "Aurkitzen dut", "aurkitzen dut",
  "Aurkitu dugu", "aurkitu dugu",
  "Identifikazioa", "identifikazioa",
  "Jarraipena", "jarraipena",
  "Behatutako", "behatutako",
  "Erregistroa", "erregistroa",

  # Basque (Euskara)
  "Monitorizazioa", "monitorizazioa",
  "Monitorizatu", "monitorizatu", "Monitorizatua", "monitorizatua", "Monitorizatzen", "monitorizatzen",
  "Zaintza", "zaintza",
  "Jarraitu", "jarraitu", "Jarraitua", "jarraitua", "Jarraitzen", "jarraitzen",

  # Basque (Euskara)
  "Aurkikuntza berria", "aurkikuntza berria",
  "Ikusita", "ikusita",
  "Agertu", "agertu", "Agertzen", "agertzen", "Agertu da", "agertu da", "Agertu dira", "agertu dira",
  "Aurkituta", "aurkituta",

  # Asturian (Asturianu)
  "Aparición", "Aparicion", "aparición", "aparicion",
  "Alerta", "alerta",
  "Avisu", "avisu",
  "Avistamientu", "avistamientu",
  "Descubrimientu", "descubrimientu",
  "Detección", "Deteccion", "detección", "deteccion",
  "Detectada", "detectada", "Detectado", "detectado",
  "Alcontrada", "alcontrada", "Alcontráu", "alcontráu",
  "Alcontré", "alcontré", "Alcontramos", "alcontramos",
  "Identificada", "identificada", "Identificáu", "identificáu",
  "Monitorización", "Monitorizacion", "monitorización", "monitorizacion",
  "Notificación", "Notificacion", "notificación", "notificacion",
  "Observada", "observada", "Observáu", "observáu",
  "Reciente", "reciente",
  "Rexistru", "rexistru",
  "Seguimientu", "seguimientu",

  # Asturian (Asturianu)
  "Monitoreu", "monitoreu",
  "Monitorizar", "monitorizar", "Monitorizáu", "monitorizáu", "Monitorizada", "monitorizada",
  "Rastrexu", "rastrexu",
  "Rastrexar", "rastrexar", "Rastrexáu", "rastrexáu", "Rastrexada", "rastrexada",

  # Asturian (Asturianu)
  "Descubiertu", "descubiertu", "Descubierta", "descubierta", "Descubiertos", "descubiertos", "Descubiertes", "descubiertes",
  "Vistu", "vistu", "Vista", "vista", "Vistos", "vistos", "Vistes", "vistes",
  "Aparecíu", "aparecíu", "Aparecida", "aparecida", "Aparecíos", "aparecíos", "Aparecíes", "aparecíes",
  "Aparez", "aparez", "Aparecieron", "aparecieron",
  
  # Spanish (Español)
  "Trampa", "trampa", "Trampas", "trampas",
  "Captura", "captura", "Capturas", "capturas",
  "Capturar", "capturar", "Capturado", "capturado", "Capturada", "capturada", "Capturados", "capturados", "Capturadas", "capturadas",
  "Control", "control", "Controlar", "controlar", "Controlado", "controlado", "Controlada", "controlada",
  "Manejo", "manejo",
  "Aparezca", "aparezca", "Aparecer", "aparecer", "Aparecido", "aparecido", "Aparecida", "aparecida",

  # Portuguese (Portugal)
  "Armadilha", "armadilha", "Armadilhas", "armadilhas",
  "Captura", "captura", "Capturas", "capturas",
  "Capturar", "capturar", "Capturado", "capturado", "Capturada", "capturada",
  "Controlo", "controlo", "Controlar", "controlar", "Controlado", "controlado", "Controlada", "controlada",
  "Gestão", "gestão",
  "Apareça", "apareça", "Aparecer", "aparecer", "Aparecido", "aparecido", "Aparecida", "aparecida",

  # Catalan (Català)
  "Trampa", "trampa", "Trampes", "trampes",
  "Captura", "captura", "Captures", "captures",
  "Capturar", "capturar", "Capturat", "capturat", "Capturada", "capturada",
  "Control", "control", "Controlar", "controlar", "Controlat", "controlat", "Controlada", "controlada",
  "Gestió", "gestió",
  "Aparegui", "aparegui", "Apareixer", "apareixer", "Aparegut", "aparegut", "Apareguda", "apareguda",

  # Galician (Galego)
  "Trampa", "trampa", "Trampas", "trampas",
  "Captura", "captura", "Capturas", "capturas",
  "Capturar", "capturar", "Capturado", "capturado", "Capturada", "capturada",
  "Control", "control", "Controlar", "controlar", "Controlado", "controlado", "Controlada", "controlada",
  "Xestión", "xestión",
  "Apareza", "apareza", "Aparecer", "aparecer", "Aparecido", "aparecido", "Aparecida", "aparecida",

  # Basque (Euskara)
  "Tranpa", "tranpa", "Tranpak", "tranpak",
  "Harrapaketa", "harrapaketa",
  "Harrapatu", "harrapatu", "Harrapatua", "harrapatua", "Harrapatuta", "harrapatuta",
  "Kontrola", "kontrola", "Kontrolatu", "kontrolatu", "Kontrolatua", "kontrolatua",
  "Kudeaketa", "kudeaketa",
  "Agertu", "agertu", "Agertzen", "agertzen", "Agertzea", "agertzea",

  # Asturian (Asturianu)
  "Trampa", "trampa", "Trampes", "trampes",
  "Captura", "captura", "Captures", "captures",
  "Capturar", "capturar", "Capturáu", "capturáu", "Capturada", "capturada",
  "Control", "control", "Controlar", "controlar", "Controláu", "controláu", "Controlada", "controlada",
  "Maneu", "maneu", "Manejar", "manejar",
  "Apaezca", "apaezca", "Aparecer", "aparecer", "Aparecíu", "aparecíu", "Aparecida", "aparecida"
)


eCommerce <- c(
  # Spanish (Español)
  "Adquisición", "Adquisicion", "adquisición", "adquisicion",
  "He adquirido", "he adquirido", "Compré", "compré", "He comprado", "he comprado",
  "Barata", "barata", "Barato", "barato", "Caro", "caro", "Cara", "cara",
  "Compra", "compra", "Comprar", "comprar",
  "Comercio", "comercio",
  "Contrabando", "contrabando",
  "Dinero", "dinero", "Euros", "euros",
  "Intercambio", "intercambio",
  "Mercado", "mercado", "Mercado negro", "mercado negro",
  "Mascota", "mascota",
  "Prohibido", "prohibido", "Prohibida", "prohibida",
  "Venta", "venta", "Vender", "vender", "Venta ilegal", "venta ilegal",
  "Coste", "coste", "Costes", "costes", "Costo", "costo", "Costos", "costos",
  "Jaula", "jaula", "Enjaulado", "enjaulado",
  "Cetrería", "cetrería",
  "Tienda", "tienda",
  "Capturado", "capturado",
  "Pajarería", "pajarería",

  # Spanish (Español)
  "Precio", "precio", "Precios", "precios",
  "Comprado", "comprado", "Comprada", "comprada", "Comprados", "comprados", "Compradas", "compradas",
  "Vendido", "vendido", "Vendida", "vendida", "Vendidos", "vendidos", "Vendidas", "vendidas",
  "Vendí", "vendí",
  # Spanish (Español)
  "Oferta", "oferta", "Ofertas", "ofertas", "Descuento", "descuento", "Descuentos", "descuentos",
  "Rebaja", "rebaja", "Rebajas", "rebajas", "Subasta", "subasta", "Subastas", "subastas",
  "Precio de venta", "precio de venta", "Precio final", "precio final",

  # Portuguese (Portugal)
  "Aquisição", "Aquisicao", "aquisição", "aquisicao",
  "Comprei", "comprei", "Tenho comprado", "tenho comprado",
  "Barata", "barata", "Barato", "barato", "Caro", "caro", "Cara", "cara",
  "Compra", "compra", "Comprar", "comprar",
  "Comércio", "Comercio", "comércio", "comercio",
  "Contrabando", "contrabando",
  "Dinheiro", "dinheiro", "Euros", "euros",
  "Intercâmbio", "Intercambio", "intercâmbio", "intercambio",
  "Mercado", "mercado", "Mercado negro", "mercado negro",
  "Mascote", "mascote",
  "Proibido", "proibido", "Proibida", "proibida",
  "Venda", "venda", "Vender", "vender", "Venda ilegal", "venda ilegal",
  "Custo", "custo", "Custos", "custos",
  "Gaiola", "gaiola", "Enjaulado", "enjaulado",
  "Falcoaria", "falcoaria",
  "Loja", "loja",
  "Capturado", "capturado",
  "Loja de aves", "pajareria", "Pajararia",

  # Portuguese (Portugal)
  "Preço", "preço", "Preços", "preços", "Preco", "preco", "Precos", "precos",
  "Comprado", "comprado", "Comprada", "comprada", "Comprados", "comprados", "Compradas", "compradas",
  "Vendido", "vendido", "Vendida", "vendida", "Vendidos", "vendidos", "Vendidas", "vendidas",
  "Vendi", "vendi",
  "Oferta", "oferta", "Ofertas", "ofertas", "Desconto", "desconto", "Descontos", "descontos",
  "Promoção", "promocao", "Promoções", "promocoes",
  "Leilão", "leilao", "Leilões", "leiloes",

  # Catalan (Català)
  "Adquisició", "Adquisicio", "adquisició", "adquisicio",
  "He adquirit", "he adquirit", "He comprat", "he comprat", "Vaig comprar", "vaig comprar",
  "Barata", "barata", "Barat", "barat", "Car", "car", "Cara", "cara",
  "Compra", "compra", "Comprar", "comprar",
  "Comerç", "comerç",
  "Contraban", "contraban",
  "Diners", "diners", "Euros", "euros",
  "Intercanvi", "intercanvi",
  "Mercat", "mercat", "Mercat negre", "mercat negre",
  "Mascota", "mascota",
  "Prohibit", "prohibit", "Prohibida", "prohibida",
  "Venda", "venda", "Vendre", "vendre", "Venda il·legal", "venda il·legal",
  "Cost", "cost", "Costos", "costos",
  "Gàbia", "gàbia", "Enjaulat", "enjaulat",
  "Cetreria", "cetreria",
  "Botiga", "botiga",
  "Capturat", "capturat",
  "Perruqueria d’ocells", "pajareria", "Ocelleria",

  # Catalan (Català)
  "Preu", "preu", "Preus", "preus",
  "Comprat", "comprat", "Comprada", "comprada", "Comprats", "comprats", "Comprades", "comprades",
  "Venut", "venut", "Venuda", "venuda", "Venuts", "venuts", "Venudes", "venudes",
  "Vaig vendre", "vaig vendre", "He venut", "he venut",
  "Oferta", "oferta", "Ofertes", "ofertes", "Descompte", "descompte", "Descomptes", "descomptes",
  "Rebaixa", "rebaixa", "Rebaixes", "rebaixes",
  "Subhasta", "subhasta", "Subhastes", "subhastes",

  # Galician (Galego)
  "Adquisición", "Adquisicion", "adquisición", "adquisicion",
  "Merquei", "merquei", "Teño mercado", "teño mercado", "Teño comprado", "teño comprado",
  "Barata", "barata", "Barato", "barato", "Caro", "caro", "Cara", "cara",
  "Compra", "compra", "Comprar", "comprar",
  "Comercio", "comercio",
  "Contrabando", "contrabando",
  "Cartos", "cartos", "Euros", "euros",
  "Intercambio", "intercambio",
  "Mercado", "mercado", "Mercado negro", "mercado negro",
  "Mascota", "mascota",
  "Prohibido", "prohibido", "Prohibida", "prohibida",
  "Venda", "venda", "Vender", "vender", "Venda ilegal", "venda ilegal",
  "Custo", "custo", "Custos", "custos",
  "Xaila", "xaila", "Enjaulado", "enjaulado",
  "Cetraría", "cetraría",
  "Tenda", "tenda",
  "Capturado", "capturado",
  "Paxaría", "paxaría",

  # Galician (Galego)
  "Prezo", "prezo", "Prezos", "prezos",
  "Comprado", "comprado", "Comprada", "comprada", "Comprados", "comprados", "Compradas", "compradas",
  "Vendido", "vendido", "Vendida", "vendida", "Vendidos", "vendidos", "Vendidas", "vendidas",
  "Vendín", "vendín",
  "Oferta", "oferta", "Ofertas", "ofertas", "Desconto", "desconto", "Descontos", "descontos",
  "Rebaixa", "rebaixa", "Rebaixas", "rebaixas", "Poxa", "poxa", "Poxas", "poxas",
  "Gaiola", "gaiola", "Gaiolas", "gaiolas",

  # Basque (Euskara)
  "Erosketa", "erosketa",
  "Erosi dut", "erosi dut", "Erosi nuen", "erosi nuen",
  "Merkea", "merkea", "Garestia", "garestia",
  "Erosi", "erosi",
  "Merkataritza", "merkataritza",
  "Kontrabandoa", "kontrabandoa",
  "Dirua", "dirua", "Euroak", "euroak",
  "Merkatua", "merkatuan", "Merkatu beltza", "merkatu beltza",
  "Maskota", "maskota",
  "Debekatua", "debekatua",
  "Salmenta", "salmenta", "Saldu", "saldu", "Ilegal salmenta", "ilegal salmenta",
  "Kostua", "kostua", "Kostuak", "kostuak",
  "Kaiola", "kaiola", "Kaiolatua", "kaiolatua",
  "Harrapari-hegaztitza", "harrapari-hegaztitza",
  "Denda", "denda",
  "Harrapatua", "harrapatua",
  "Txori-denda", "txoridenda",

  # Basque (Euskara)
  "Prezioa", "prezioa", "Prezio", "prezio", "Prezioak", "prezioak",
  "Erosi dut", "Erosi dugu", "Erosi du", "Erosi dute",
  "Saldu dut", "saldu dut", "Saldua", "saldua", "Saltzea", "saltzea",
  "Eskaintza", "eskaintza", "Deskontoa", "deskontoa", "Deskontoak", "deskontoak",
  "Enkantea", "enkantea", "Enkanteak", "enkanteak",

  # Asturian (Asturianu)
  "Adquisición", "Adquisicion", "adquisición", "adquisicion",
  "Compré", "compré", "He mercáu", "he mercáu", "He compráu", "he compráu",
  "Barata", "barata", "Baratu", "baratu", "Caro", "caro", "Cara", "cara",
  "Compra", "compra", "Comprar", "comprar",
  "Comerciu", "comerciu",
  "Contrabandu", "contrabandu",
  "Perres", "perres", "Euros", "euros",
  "Intercambiu", "intercambiu",
  "Mercáu", "mercáu", "Mercáu negru", "mercáu negru",
  "Mascota", "mascota",
  "Prohibíu", "prohibíu", "Prohibida", "prohibida",
  "Venta", "venta", "Vender", "vender", "Venta ilegal", "venta ilegal",
  "Costu", "costu", "Costos", "costos",
  "Caxa", "caxa", "Enjauláu", "enjauláu",
  "Cetrería", "cetrería",
  "Tienda", "tienda", "Tienda", "tienda",
  "Capturáu", "capturáu",
  "Pajarería", "pajarería",

  # Asturian (Asturianu)
  "Preciu", "preciu", "Precios", "precios",
  "Compráu", "compráu", "Comprada", "comprada", "Compraos", "compraos", "Compraes", "compraes",
  "Vendidu", "vendidu", "Vendida", "vendida", "Vendíos", "vendíos", "Vendíes", "vendíes",
  "Vendí", "vendí",
  "Oferta", "oferta", "Ofertes", "ofertes", "Descuentu", "descuentu", "Descuentos", "descuentos",
  "Rebaxa", "rebaxa", "Rebaxes", "rebaxes", "Subasta", "subasta", "Subastes", "subastes",

  # =========================
  # Adoption and trade-related terms
  # =========================
  "Adoptar", "adoptar",
  "Adopción", "Adopcion", "adopción", "adopcion",
  "Adoptado", "adoptado", "Adoptada", "adoptada", "Adoptados", "adoptados", "Adoptadas", "adoptadas",
  "Adopto", "adopto", "Adopta", "adopta", "Adoptas", "adoptas", "Adoptamos", "adoptamos", "Adoptan", "adoptan",
  "Adopté", "adopté", "Adoptó", "adoptó", "Adoptaste", "adoptaste", "Adoptaron", "adoptaron",
  "Adoptaré", "adoptaré", "Adoptará", "adoptará", "Adoptaremos", "adoptaremos", "Adoptarán", "adoptarán",
  "Adotar", "adotar",
  "Adoção", "Adocao", "adoção", "adocao",
  "Adotado", "adotado", "Adotada", "adotada", "Adotados", "adotados", "Adotadas", "adotadas",
  "Adoto", "adoto", "Adota", "adota", "Adotas", "adotas", "Adotamos", "adotamos", "Adotam", "adotam",
  "Adotei", "adotei", "Adotou", "adotou", "Adotaste", "adotaste", "Adotaram", "adotaram",
  "Adotarei", "adotarei", "Adotará", "adotará", "Adotaremos", "adotaremos", "Adotarão", "adotarão",
  "Adopció", "Adopcio", "adopció", "adopcio",
  "Adoptat", "adoptat", "Adoptada", "adoptada", "Adoptats", "adoptats", "Adoptades", "adoptades",
  "Adopto", "adopto", "Adopta", "adopta", "Adoptes", "adoptes", "Adoptem", "adoptem", "Adopten", "adopten",
  "Vaig adoptar", "vaig adoptar", "Va adoptar", "va adoptar", "Vas adoptar", "vas adoptar", "Van adoptar", "van adoptar",
  "Adoptaré", "adoptaré", "Adoptarà", "adoptarà", "Adoptarem", "adoptarem", "Adoptaran", "adoptaran",
  "Adoptar", "adoptar",
  "Adopción", "Adopcion", "adopción", "adopcion",
  "Adoptado", "adoptado", "Adoptada", "adoptada", "Adoptados", "adoptados", "Adoptadas", "adoptadas",
  "Adopto", "adopto", "Adopta", "adopta", "Adoptas", "adoptas", "Adoptamos", "adoptamos", "Adoptan", "adoptan",
  "Adoptei", "adoptei", "Adoptou", "adoptou", "Adoptaches", "adoptaches", "Adoptaron", "adoptaron",
  "Adoptarei", "adoptarei", "Adoptará", "adoptará", "Adoptaremos", "adoptaremos", "Adoptarán", "adoptarán",
  "Adoptatu", "adoptatu",
  "Adoptatua", "adoptatua", "Adoptatutako", "adoptatutako",
  "Adoptatzen dut", "adoptatzen dut", "Adoptatzen du", "adoptatzen du",
  "Adoptatuko dut", "adoptatuko dut", "Adoptatuko du", "adoptatuko du",
  "Adoptar", "adoptar",
  "Adopción", "Adopcion", "adopción", "adopcion",
  "Adoptáu", "adoptáu", "Adoptada", "adoptada", "Adoptados", "adoptados", "Adoptadas", "adoptadas",
  "Adopto", "adopto", "Adopta", "adopta", "Adoptes", "adoptes", "Adoptamos", "adoptamos", "Adopten", "adopten",
  "Adopté", "adopté", "Adoptó", "adoptó", "Adoptasti", "adoptasti", "Adoptaron", "adoptaron",
  "Adoptaré", "adoptaré", "Adoptará", "adoptará", "Adoptaremos", "adoptaremos", "Adoptarán", "adoptarán",

  # =========================
  # Aquarium / Fish tank terms (kept)
  # =========================
  "Acuario", "acuario", "Acuarios", "acuarios",
  "Pecera", "pecera", "Peceras", "peceras",
  "Aquário", "Aquario", "aquário", "aquario", "Aquários", "Aquarios", "aquários", "aquarios",
  "Aquário de peixes", "aquário de peixes", "Aquarios de peixes", "aquarios de peixes",
  "Aquari", "aquari", "Aquaris", "aquaris",
  "Peixera", "peixera", "Peixeres", "peixeres",
  "Acuario", "acuario", "Acuarios", "acuarios",
  "Peixeira", "peixeira", "Peixeiras", "peixeiras",
  "Akuario", "akuario", "Akuarioak", "akuarioak",
  "Arrainontzi", "arrainontzi", "Arrainontziak", "arrainontziak",
  "Acuariu", "acuariu", "Acuarios", "acuarios",
  "Pecera", "pecera", "Peceres", "peceres",
  
  # Spanish (Español)
  "Terrario", "terrario", "Terrarios", "terrarios",

  # Portuguese (Portugal)
  "Terrário", "Terrario", "terrário", "terrario",
  "Terrários", "Terrarios", "terrários", "terrarios",

  # Catalan (Català)
  "Terrari", "terrari", "Terraris", "terraris",

  # Galician (Galego)
  "Terrario", "terrario", "Terrarios", "terrarios",

  # Basque (Euskara)
  "Terrario", "terrario", "Terrarioak", "terrarioak",

  # Asturian (Asturianu)
  "Terrariu", "terrariu", "Terrarios", "terrarios",
  
  # Spanish (Español)
  "Envío a", "envío a", "Envio a", "envio a",
  "Envíos a", "envíos a", "Envios a", "envios a",

  # Portuguese (Portugal)
  "Envio para", "envio para",
  "Envios para", "envios para",

  # Catalan (Català)
  "Enviament a", "enviament a",
  "Enviaments a", "enviaments a",

  # Galician (Galego)
  "Envío a", "envío a", "Envio a", "envio a",
  "Envíos a", "envíos a", "Envios a", "envios a",

  # Basque (Euskara)
  "Bidalketa", "bidalketa",  # shipment
  "Bidalketak", "bidalketak",  # shipments
  "Bidalketa hona", "bidalketa hona",
  "Bidalketak hona", "bidalketak hona",

  # Asturian (Asturianu)
  "Unvíu a", "unvíu a",
  "Unvíos a", "unvíos a",
  
  # Spanish (Español)
  "Me costó", "me costó", "Me costaron", "me costaron",
  "Caza furtiva", "caza furtiva",
  "En cautividad", "en cautividad",

  # Portuguese (Portugal)
  "Custou-me", "custou-me", "Custaram-me", "custaram-me",
  "Caça furtiva", "caça furtiva",
  "Em cativeiro", "em cativeiro",

  # Catalan (Català)
  "Em va costar", "em va costar", "Em van costar", "em van costar",
  "Caça furtiva", "caça furtiva",
  "En captivitat", "en captivitat",

  # Galician (Galego)
  "Custoume", "custoume", "Custáronme", "custáronme",
  "Caza furtiva", "caza furtiva",
  "En catividade", "en catividade",

  # Basque (Euskara)
  "Kostatu zitzaidan", "kostatu zitzaidan", "Kostatu zitzaizkidan", "kostatu zitzaizkidan",
  "Furtibo ehiza", "furtibo ehiza",
  "Esparruan", "esparruan", "Kaiola batean", "kaiola batean",  # “in captivity” ? in enclosure/cage

  # Asturian (Asturianu)
  "Costóme", "costóme", "Costáronme", "costáronme",
  "Caza furtiva", "caza furtiva",
  "En cautividá", "en cautividá"
)